### ISSUE TITLE
32X hack doesn't work

### ISSUE THREAD

**Issue by Agentmanbh** [jvisser/msu-md-mk2#1]
Test on real MD1 JP + 32X + JU MKII ROM with Mega Everdrive PRO.

With Warning Option enabled, give this message:
"This ROM conflicts With 32x addon."

Anyway, hacked ROM doesn't work with Warning Option disabled (black screen).

**Comment by jvisser** [comment]
msu-md does not work with mega everdrive pro when inserted into the 32x. You need a real mega cd then or connect the flashcard to the expansion port of the mega drive somehow.

See this reply from krikzz https://twitter.com/djshawd1/status/1364637473196765186?s=19

Same for megasd/md+ at this time btw.

**Comment by Agentmanbh** [comment]
Ok, then is a dead end...I forgot 32X games only works with 32X add-on attached, but MSU don't works with it.
Only will work if burn a CD-r and play with both add-ons attached, or emulated.
Thanks for your attention!

**Comment by jvisser** [comment]
Yeah unfortunately so. Also when connecting the flashcard to the expansion port as a mega cd you would still need another flashcard for the 32x. Not ideal.

**Comment by palmerj** [comment]
Is is possible to make a patch that works with emulators. e.g picodrive?

**Comment by jvisser** [comment]
@palmerj 
Check here for emulation: https://www.zeldix.net/t2175-md-32x-emulators-genesis-plus-gx-picodrive-mame
And for the patches here: https://www.zeldix.net/t2305-mortal-kombat-ii-md-32x-msu-md

**Comment by palmerj** [comment]
So not possible? What is the limitation for emulators?

**Comment by jvisser** [comment]
Use the 32x+ patch... Anyway this is not the place to ask this question as it's the emulator that needs to support this patch not the other way arround.

**Comment by palmerj** [comment]
I used Use the 32x+ patch and the retroarch picodrive emulation didn't have any sound. Ok I will raise the issue over here https://github.com/notaz/picodrive

**Comment by palmerj** [comment]
Picodrive issue raised here https://github.com/notaz/picodrive/issues/163
